version: '3'
services:
  postgres-talent:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/usr/local/pgsql/data
    environment:
      POSTGRES_DB: talent
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres-data: